export const countriesHashmap = {
  Italy: 0,
  Spain: 1,
  Germany: 2,
  China: 3,
  France: 4,
  Iran: 5,
  US: 6,
  "United Kingdom": 7,
  Switzerland: 8,
  Turkey: 9,
  Belgium: 10,
  Netherlands: 11,
  Austria: 12,
  "Korea, South": 13,
  Portugal: 14,
  Brazil: 15,
  Israel: 16,
  Norway: 17,
  Sweden: 18,
  Canada: 19,
  Czechia: 20,
  Ireland: 21,
  Denmark: 22,
  Malaysia: 23,
  Chile: 24,
  Poland: 25,
  Russia: 26,
  Ecuador: 27,
  Romania: 28,
  Australia: 29,
  Japan: 30,
  Luxembourg: 31,
  Philippines: 32,
  Pakistan: 33,
  Thailand: 34,
  India: 35,
  "Saudi Arabia": 36,
  Indonesia: 37,
  Finland: 38,
  "South Africa": 39,
  Greece: 40,
  Mexico: 41,
  Panama: 42,
  Iceland: 43,
  "Dominican Republic": 44,
  Peru: 45,
  Argentina: 46,
  Singapore: 47,
  Colombia: 48,
  Serbia: 49,
  Croatia: 50,
  Slovenia: 51,
  Qatar: 52,
  Estonia: 53,
  Algeria: 54,
  "Diamond Princess": 55,
  Egypt: 56,
  "New Zealand": 57,
  Iraq: 58,
  Ukraine: 59,
  "United Arab Emirates": 60,
  Morocco: 61,
  Lithuania: 62,
  Armenia: 63,
  Bahrain: 64,
  Hungary: 65,
  Lebanon: 66,
  Latvia: 67,
  "Bosnia and Herzegovina": 68,
  Bulgaria: 69,
  Tunisia: 70,
  Andorra: 71,
  Kazakhstan: 72,
  Slovakia: 73,
  Moldova: 74,
  "Costa Rica": 75,
  Uruguay: 76,
  "North Macedonia": 77,
  "Taiwan*": 78,
  Azerbaijan: 79,
  Kuwait: 80,
  Jordan: 81,
  Cyprus: 82,
  "Burkina Faso": 83,
  Albania: 84,
  "San Marino": 85,
  Cameroon: 86,
  Vietnam: 87,
  Oman: 88,
  Afghanistan: 89,
  Cuba: 90,
  "Cote d'Ivoire": 91,
  Senegal: 92,
  Uzbekistan: 93,
  Honduras: 94,
  Malta: 95,
  Belarus: 96,
  Ghana: 97,
  Mauritius: 98,
  "Sri Lanka": 99,
  Venezuela: 100,
  Nigeria: 101,
  Brunei: 102,
  Montenegro: 103,
  "West Bank and Gaza": 104,
  Bolivia: 105,
  Georgia: 106,
  Kosovo: 107,
  Kyrgyzstan: 108,
  Cambodia: 109,
  "Congo (Kinshasa)": 110,
  "Trinidad and Tobago": 111,
  Rwanda: 112,
  Liechtenstein: 113,
  Paraguay: 114,
  Kenya: 115,
  Madagascar: 116,
  Bangladesh: 117,
  Monaco: 118,
  Uganda: 119,
  Guatemala: 120,
  Jamaica: 121,
  Zambia: 122,
  Barbados: 123,
  Niger: 124,
  Togo: 125,
  "El Salvador": 126,
  Djibouti: 127,
  Mali: 128,
  Ethiopia: 129,
  Guinea: 130,
  "Congo (Brazzaville)": 131,
  Tanzania: 132,
  Gabon: 133,
  Maldives: 134,
  Haiti: 135,
  Bahamas: 136,
  Burma: 137,
  "Equatorial Guinea": 138,
  Eritrea: 139,
  Mongolia: 140,
  "Saint Lucia": 141,
  Dominica: 142,
  Guyana: 143,
  Namibia: 144,
  Libya: 145,
  Seychelles: 146,
  Suriname: 147,
  Syria: 148,
  Benin: 149,
  Eswatini: 150,
  Grenada: 151,
  Laos: 152,
  "Guinea-Bissau": 153,
  Mozambique: 154,
  "Saint Kitts and Nevis": 155,
  Zimbabwe: 156,
  Angola: 157,
  "Antigua and Barbuda": 158,
  Chad: 159,
  Sudan: 160,
  "Cabo Verde": 161,
  "Holy See": 162,
  Mauritania: 163,
  Fiji: 164,
  Nepal: 165,
  Nicaragua: 166,
  Somalia: 167,
  Bhutan: 168,
  Botswana: 169,
  Gambia: 170,
  Belize: 171,
  "Central African Republic": 172,
  Liberia: 173,
  Burundi: 174,
  "MS Zaandam": 175,
  "Papua New Guinea": 176,
  "Saint Vincent and the Grenadines": 177,
  "Sierra Leone": 178,
  "Timor-Leste": 179,
}

export const countries = [
  { country: "Italy", confirmedCount: 0 },
  { country: "Spain", confirmedCount: 0 },
  { country: "Germany", confirmedCount: 0 },
  { country: "China", confirmedCount: 0 },
  { country: "France", confirmedCount: 0 },
  { country: "Iran", confirmedCount: 0 },
  { country: "US", confirmedCount: 0 },
  { country: "United Kingdom", confirmedCount: 0 },
  { country: "Switzerland", confirmedCount: 0 },
  { country: "Turkey", confirmedCount: 0 },
  { country: "Belgium", confirmedCount: 0 },
  { country: "Netherlands", confirmedCount: 0 },
  { country: "Austria", confirmedCount: 0 },
  { country: "Korea, South", confirmedCount: 0 },
  { country: "Portugal", confirmedCount: 0 },
  { country: "Brazil", confirmedCount: 0 },
  { country: "Israel", confirmedCount: 0 },
  { country: "Norway", confirmedCount: 0 },
  { country: "Sweden", confirmedCount: 0 },
  { country: "Canada", confirmedCount: 0 },
  { country: "Czechia", confirmedCount: 0 },
  { country: "Ireland", confirmedCount: 0 },
  { country: "Denmark", confirmedCount: 0 },
  { country: "Malaysia", confirmedCount: 0 },
  { country: "Chile", confirmedCount: 0 },
  { country: "Poland", confirmedCount: 0 },
  { country: "Russia", confirmedCount: 0 },
  { country: "Ecuador", confirmedCount: 0 },
  { country: "Romania", confirmedCount: 0 },
  { country: "Australia", confirmedCount: 0 },
  { country: "Japan", confirmedCount: 0 },
  { country: "Luxembourg", confirmedCount: 0 },
  { country: "Philippines", confirmedCount: 0 },
  { country: "Pakistan", confirmedCount: 0 },
  { country: "Thailand", confirmedCount: 0 },
  { country: "India", confirmedCount: 0 },
  { country: "Saudi Arabia", confirmedCount: 0 },
  { country: "Indonesia", confirmedCount: 0 },
  { country: "Finland", confirmedCount: 0 },
  { country: "South Africa", confirmedCount: 0 },
  { country: "Greece", confirmedCount: 0 },
  { country: "Mexico", confirmedCount: 0 },
  { country: "Panama", confirmedCount: 0 },
  { country: "Iceland", confirmedCount: 0 },
  { country: "Dominican Republic", confirmedCount: 0 },
  { country: "Peru", confirmedCount: 0 },
  { country: "Argentina", confirmedCount: 0 },
  { country: "Singapore", confirmedCount: 0 },
  { country: "Colombia", confirmedCount: 0 },
  { country: "Serbia", confirmedCount: 0 },
  { country: "Croatia", confirmedCount: 0 },
  { country: "Slovenia", confirmedCount: 0 },
  { country: "Qatar", confirmedCount: 0 },
  { country: "Estonia", confirmedCount: 0 },
  { country: "Algeria", confirmedCount: 0 },
  { country: "Diamond Princess", confirmedCount: 0 },
  { country: "Egypt", confirmedCount: 0 },
  { country: "New Zealand", confirmedCount: 0 },
  { country: "Iraq", confirmedCount: 0 },
  { country: "Ukraine", confirmedCount: 0 },
  { country: "United Arab Emirates", confirmedCount: 0 },
  { country: "Morocco", confirmedCount: 0 },
  { country: "Lithuania", confirmedCount: 0 },
  { country: "Armenia", confirmedCount: 0 },
  { country: "Bahrain", confirmedCount: 0 },
  { country: "Hungary", confirmedCount: 0 },
  { country: "Lebanon", confirmedCount: 0 },
  { country: "Latvia", confirmedCount: 0 },
  { country: "Bosnia and Herzegovina", confirmedCount: 0 },
  { country: "Bulgaria", confirmedCount: 0 },
  { country: "Tunisia", confirmedCount: 0 },
  { country: "Andorra", confirmedCount: 0 },
  { country: "Kazakhstan", confirmedCount: 0 },
  { country: "Slovakia", confirmedCount: 0 },
  { country: "Moldova", confirmedCount: 0 },
  { country: "Costa Rica", confirmedCount: 0 },
  { country: "Uruguay", confirmedCount: 0 },
  { country: "North Macedonia", confirmedCount: 0 },
  { country: "Taiwan*", confirmedCount: 0 },
  { country: "Azerbaijan", confirmedCount: 0 },
  { country: "Kuwait", confirmedCount: 0 },
  { country: "Jordan", confirmedCount: 0 },
  { country: "Cyprus", confirmedCount: 0 },
  { country: "Burkina Faso", confirmedCount: 0 },
  { country: "Albania", confirmedCount: 0 },
  { country: "San Marino", confirmedCount: 0 },
  { country: "Cameroon", confirmedCount: 0 },
  { country: "Vietnam", confirmedCount: 0 },
  { country: "Oman", confirmedCount: 0 },
  { country: "Afghanistan", confirmedCount: 0 },
  { country: "Cuba", confirmedCount: 0 },
  { country: "Cote d'Ivoire", confirmedCount: 0 },
  { country: "Senegal", confirmedCount: 0 },
  { country: "Uzbekistan", confirmedCount: 0 },
  { country: "Honduras", confirmedCount: 0 },
  { country: "Malta", confirmedCount: 0 },
  { country: "Belarus", confirmedCount: 0 },
  { country: "Ghana", confirmedCount: 0 },
  { country: "Mauritius", confirmedCount: 0 },
  { country: "Sri Lanka", confirmedCount: 0 },
  { country: "Venezuela", confirmedCount: 0 },
  { country: "Nigeria", confirmedCount: 0 },
  { country: "Brunei", confirmedCount: 0 },
  { country: "Montenegro", confirmedCount: 0 },
  { country: "West Bank and Gaza", confirmedCount: 0 },
  { country: "Bolivia", confirmedCount: 0 },
  { country: "Georgia", confirmedCount: 0 },
  { country: "Kosovo", confirmedCount: 0 },
  { country: "Kyrgyzstan", confirmedCount: 0 },
  { country: "Cambodia", confirmedCount: 0 },
  { country: "Congo (Kinshasa)", confirmedCount: 0 },
  { country: "Trinidad and Tobago", confirmedCount: 0 },
  { country: "Rwanda", confirmedCount: 0 },
  { country: "Liechtenstein", confirmedCount: 0 },
  { country: "Paraguay", confirmedCount: 0 },
  { country: "Kenya", confirmedCount: 0 },
  { country: "Madagascar", confirmedCount: 0 },
  { country: "Bangladesh", confirmedCount: 0 },
  { country: "Monaco", confirmedCount: 0 },
  { country: "Uganda", confirmedCount: 0 },
  { country: "Guatemala", confirmedCount: 0 },
  { country: "Jamaica", confirmedCount: 0 },
  { country: "Zambia", confirmedCount: 0 },
  { country: "Barbados", confirmedCount: 0 },
  { country: "Niger", confirmedCount: 0 },
  { country: "Togo", confirmedCount: 0 },
  { country: "El Salvador", confirmedCount: 0 },
  { country: "Djibouti", confirmedCount: 0 },
  { country: "Mali", confirmedCount: 0 },
  { country: "Ethiopia", confirmedCount: 0 },
  { country: "Guinea", confirmedCount: 0 },
  { country: "Congo (Brazzaville)", confirmedCount: 0 },
  { country: "Tanzania", confirmedCount: 0 },
  { country: "Gabon", confirmedCount: 0 },
  { country: "Maldives", confirmedCount: 0 },
  { country: "Haiti", confirmedCount: 0 },
  { country: "Bahamas", confirmedCount: 0 },
  { country: "Burma", confirmedCount: 0 },
  { country: "Equatorial Guinea", confirmedCount: 0 },
  { country: "Eritrea", confirmedCount: 0 },
  { country: "Mongolia", confirmedCount: 0 },
  { country: "Saint Lucia", confirmedCount: 0 },
  { country: "Dominica", confirmedCount: 0 },
  { country: "Guyana", confirmedCount: 0 },
  { country: "Namibia", confirmedCount: 0 },
  { country: "Libya", confirmedCount: 0 },
  { country: "Seychelles", confirmedCount: 0 },
  { country: "Suriname", confirmedCount: 0 },
  { country: "Syria", confirmedCount: 0 },
  { country: "Benin", confirmedCount: 0 },
  { country: "Eswatini", confirmedCount: 0 },
  { country: "Grenada", confirmedCount: 0 },
  { country: "Laos", confirmedCount: 0 },
  { country: "Guinea-Bissau", confirmedCount: 0 },
  { country: "Mozambique", confirmedCount: 0 },
  { country: "Saint Kitts and Nevis", confirmedCount: 0 },
  { country: "Zimbabwe", confirmedCount: 0 },
  { country: "Angola", confirmedCount: 0 },
  { country: "Antigua and Barbuda", confirmedCount: 0 },
  { country: "Chad", confirmedCount: 0 },
  { country: "Sudan", confirmedCount: 0 },
  { country: "Cabo Verde", confirmedCount: 0 },
  { country: "Holy See", confirmedCount: 0 },
  { country: "Mauritania", confirmedCount: 0 },
  { country: "Fiji", confirmedCount: 0 },
  { country: "Nepal", confirmedCount: 0 },
  { country: "Nicaragua", confirmedCount: 0 },
  { country: "Somalia", confirmedCount: 0 },
  { country: "Bhutan", confirmedCount: 0 },
  { country: "Botswana", confirmedCount: 0 },
  { country: "Gambia", confirmedCount: 0 },
  { country: "Belize", confirmedCount: 0 },
  { country: "Central African Republic", confirmedCount: 0 },
  { country: "Liberia", confirmedCount: 0 },
  { country: "Burundi", confirmedCount: 0 },
  { country: "MS Zaandam", confirmedCount: 0 },
  { country: "Papua New Guinea", confirmedCount: 0 },
  { country: "Saint Vincent and the Grenadines", confirmedCount: 0 },
  { country: "Sierra Leone", confirmedCount: 0 },
  { country: "Timor-Leste", confirmedCount: 0 },
]
