export const countriesHashmap = {
  Italy: 0,
  Spain: 1,
  China: 2,
  Germany: 3,
  Iran: 4,
  France: 5,
  US: 6,
  "United Kingdom": 7,
  Switzerland: 8,
  Belgium: 9,
  Netherlands: 10,
  Turkey: 11,
  Austria: 12,
  "Korea, South": 13,
  Portugal: 14,
  Israel: 15,
  Brazil: 16,
  Norway: 17,
  Sweden: 18,
  Canada: 19,
  Czechia: 20,
  Ireland: 21,
  Denmark: 22,
  Malaysia: 23,
  Chile: 24,
  Russia: 25,
  Romania: 26,
  Poland: 27,
  Philippines: 28,
  Australia: 29,
  Luxembourg: 30,
  Ecuador: 31,
  Japan: 32,
  Pakistan: 33,
  Thailand: 34,
  Indonesia: 35,
  "Saudi Arabia": 36,
  Finland: 37,
  "South Africa": 38,
  India: 39,
  Greece: 40,
  Mexico: 41,
  Iceland: 42,
  Panama: 43,
  Argentina: 44,
  Peru: 45,
  "Dominican Republic": 46,
  Singapore: 47,
  Slovenia: 48,
  Colombia: 49,
  Croatia: 50,
  Serbia: 51,
  Estonia: 52,
  "Diamond Princess": 53,
  Qatar: 54,
  Egypt: 55,
  "New Zealand": 56,
  Iraq: 57,
  "United Arab Emirates": 58,
  Algeria: 59,
  Morocco: 60,
  Ukraine: 61,
  Lithuania: 62,
  Armenia: 63,
  Bahrain: 64,
  Hungary: 65,
  Lebanon: 66,
  "Bosnia and Herzegovina": 67,
  Latvia: 68,
  Bulgaria: 69,
  Andorra: 70,
  Slovakia: 71,
  Tunisia: 72,
  Kazakhstan: 73,
  "Costa Rica": 74,
  "Taiwan*": 75,
  Uruguay: 76,
  Moldova: 77,
  Kuwait: 78,
  "North Macedonia": 79,
  Azerbaijan: 80,
  Jordan: 81,
  "Burkina Faso": 82,
  Albania: 83,
  Cyprus: 84,
  "San Marino": 85,
  Vietnam: 86,
  Cameroon: 87,
  Oman: 88,
  Senegal: 89,
  Afghanistan: 90,
  Cuba: 91,
  Malta: 92,
  "Cote d'Ivoire": 93,
  Uzbekistan: 94,
  Belarus: 95,
  Ghana: 96,
  Mauritius: 97,
  Honduras: 98,
  Nigeria: 99,
  Venezuela: 100,
  "Sri Lanka": 101,
  Brunei: 102,
  "West Bank and Gaza": 103,
  Georgia: 104,
  Cambodia: 105,
  Bolivia: 106,
  Kyrgyzstan: 107,
  Kosovo: 108,
  Montenegro: 109,
  "Congo (Kinshasa)": 110,
  "Trinidad and Tobago": 111,
  Rwanda: 112,
  Paraguay: 113,
  Liechtenstein: 114,
  Bangladesh: 115,
  Kenya: 116,
  Monaco: 117,
  Madagascar: 118,
  Guatemala: 119,
  Jamaica: 120,
  Zambia: 121,
  Barbados: 122,
  Uganda: 123,
  "El Salvador": 124,
  Togo: 125,
  Niger: 126,
  Ethiopia: 127,
  Mali: 128,
  Guinea: 129,
  "Congo (Brazzaville)": 130,
  Tanzania: 131,
  Djibouti: 132,
  Maldives: 133,
  Gabon: 134,
  Eritrea: 135,
  Haiti: 136,
  Bahamas: 137,
  Burma: 138,
  Dominica: 139,
  "Equatorial Guinea": 140,
  Mongolia: 141,
  Namibia: 142,
  Seychelles: 143,
  Syria: 144,
  Eswatini: 145,
  Grenada: 146,
  Laos: 147,
  "Saint Lucia": 148,
  "Guinea-Bissau": 149,
  Guyana: 150,
  Libya: 151,
  Mozambique: 152,
  Suriname: 153,
  Zimbabwe: 154,
  Angola: 155,
  "Antigua and Barbuda": 156,
  Chad: 157,
  "Saint Kitts and Nevis": 158,
  Sudan: 159,
  Benin: 160,
  "Cabo Verde": 161,
  "Holy See": 162,
  Mauritania: 163,
  Fiji: 164,
  Nepal: 165,
  Bhutan: 166,
  Gambia: 167,
  Nicaragua: 168,
  Belize: 169,
  Botswana: 170,
  "Central African Republic": 171,
  Liberia: 172,
  Somalia: 173,
  "MS Zaandam": 174,
  "Papua New Guinea": 175,
  "Saint Vincent and the Grenadines": 176,
  "Timor-Leste": 177,
}

export const countries = [
  { country: "Italy", confirmedCount: 0 },
  { country: "Spain", confirmedCount: 0 },
  { country: "China", confirmedCount: 0 },
  { country: "Germany", confirmedCount: 0 },
  { country: "Iran", confirmedCount: 0 },
  { country: "France", confirmedCount: 0 },
  { country: "US", confirmedCount: 0 },
  { country: "United Kingdom", confirmedCount: 0 },
  { country: "Switzerland", confirmedCount: 0 },
  { country: "Belgium", confirmedCount: 0 },
  { country: "Netherlands", confirmedCount: 0 },
  { country: "Turkey", confirmedCount: 0 },
  { country: "Austria", confirmedCount: 0 },
  { country: "Korea, South", confirmedCount: 0 },
  { country: "Portugal", confirmedCount: 0 },
  { country: "Israel", confirmedCount: 0 },
  { country: "Brazil", confirmedCount: 0 },
  { country: "Norway", confirmedCount: 0 },
  { country: "Sweden", confirmedCount: 0 },
  { country: "Canada", confirmedCount: 0 },
  { country: "Czechia", confirmedCount: 0 },
  { country: "Ireland", confirmedCount: 0 },
  { country: "Denmark", confirmedCount: 0 },
  { country: "Malaysia", confirmedCount: 0 },
  { country: "Chile", confirmedCount: 0 },
  { country: "Russia", confirmedCount: 0 },
  { country: "Romania", confirmedCount: 0 },
  { country: "Poland", confirmedCount: 0 },
  { country: "Philippines", confirmedCount: 0 },
  { country: "Australia", confirmedCount: 0 },
  { country: "Luxembourg", confirmedCount: 0 },
  { country: "Ecuador", confirmedCount: 0 },
  { country: "Japan", confirmedCount: 0 },
  { country: "Pakistan", confirmedCount: 0 },
  { country: "Thailand", confirmedCount: 0 },
  { country: "Indonesia", confirmedCount: 0 },
  { country: "Saudi Arabia", confirmedCount: 0 },
  { country: "Finland", confirmedCount: 0 },
  { country: "South Africa", confirmedCount: 0 },
  { country: "India", confirmedCount: 0 },
  { country: "Greece", confirmedCount: 0 },
  { country: "Mexico", confirmedCount: 0 },
  { country: "Iceland", confirmedCount: 0 },
  { country: "Panama", confirmedCount: 0 },
  { country: "Argentina", confirmedCount: 0 },
  { country: "Peru", confirmedCount: 0 },
  { country: "Dominican Republic", confirmedCount: 0 },
  { country: "Singapore", confirmedCount: 0 },
  { country: "Slovenia", confirmedCount: 0 },
  { country: "Colombia", confirmedCount: 0 },
  { country: "Croatia", confirmedCount: 0 },
  { country: "Serbia", confirmedCount: 0 },
  { country: "Estonia", confirmedCount: 0 },
  { country: "Diamond Princess", confirmedCount: 0 },
  { country: "Qatar", confirmedCount: 0 },
  { country: "Egypt", confirmedCount: 0 },
  { country: "New Zealand", confirmedCount: 0 },
  { country: "Iraq", confirmedCount: 0 },
  { country: "United Arab Emirates", confirmedCount: 0 },
  { country: "Algeria", confirmedCount: 0 },
  { country: "Morocco", confirmedCount: 0 },
  { country: "Ukraine", confirmedCount: 0 },
  { country: "Lithuania", confirmedCount: 0 },
  { country: "Armenia", confirmedCount: 0 },
  { country: "Bahrain", confirmedCount: 0 },
  { country: "Hungary", confirmedCount: 0 },
  { country: "Lebanon", confirmedCount: 0 },
  { country: "Bosnia and Herzegovina", confirmedCount: 0 },
  { country: "Latvia", confirmedCount: 0 },
  { country: "Bulgaria", confirmedCount: 0 },
  { country: "Andorra", confirmedCount: 0 },
  { country: "Slovakia", confirmedCount: 0 },
  { country: "Tunisia", confirmedCount: 0 },
  { country: "Kazakhstan", confirmedCount: 0 },
  { country: "Costa Rica", confirmedCount: 0 },
  { country: "Taiwan*", confirmedCount: 0 },
  { country: "Uruguay", confirmedCount: 0 },
  { country: "Moldova", confirmedCount: 0 },
  { country: "Kuwait", confirmedCount: 0 },
  { country: "North Macedonia", confirmedCount: 0 },
  { country: "Azerbaijan", confirmedCount: 0 },
  { country: "Jordan", confirmedCount: 0 },
  { country: "Burkina Faso", confirmedCount: 0 },
  { country: "Albania", confirmedCount: 0 },
  { country: "Cyprus", confirmedCount: 0 },
  { country: "San Marino", confirmedCount: 0 },
  { country: "Vietnam", confirmedCount: 0 },
  { country: "Cameroon", confirmedCount: 0 },
  { country: "Oman", confirmedCount: 0 },
  { country: "Senegal", confirmedCount: 0 },
  { country: "Afghanistan", confirmedCount: 0 },
  { country: "Cuba", confirmedCount: 0 },
  { country: "Malta", confirmedCount: 0 },
  { country: "Cote d'Ivoire", confirmedCount: 0 },
  { country: "Uzbekistan", confirmedCount: 0 },
  { country: "Belarus", confirmedCount: 0 },
  { country: "Ghana", confirmedCount: 0 },
  { country: "Mauritius", confirmedCount: 0 },
  { country: "Honduras", confirmedCount: 0 },
  { country: "Nigeria", confirmedCount: 0 },
  { country: "Venezuela", confirmedCount: 0 },
  { country: "Sri Lanka", confirmedCount: 0 },
  { country: "Brunei", confirmedCount: 0 },
  { country: "West Bank and Gaza", confirmedCount: 0 },
  { country: "Georgia", confirmedCount: 0 },
  { country: "Cambodia", confirmedCount: 0 },
  { country: "Bolivia", confirmedCount: 0 },
  { country: "Kyrgyzstan", confirmedCount: 0 },
  { country: "Kosovo", confirmedCount: 0 },
  { country: "Montenegro", confirmedCount: 0 },
  { country: "Congo (Kinshasa)", confirmedCount: 0 },
  { country: "Trinidad and Tobago", confirmedCount: 0 },
  { country: "Rwanda", confirmedCount: 0 },
  { country: "Paraguay", confirmedCount: 0 },
  { country: "Liechtenstein", confirmedCount: 0 },
  { country: "Bangladesh", confirmedCount: 0 },
  { country: "Kenya", confirmedCount: 0 },
  { country: "Monaco", confirmedCount: 0 },
  { country: "Madagascar", confirmedCount: 0 },
  { country: "Guatemala", confirmedCount: 0 },
  { country: "Jamaica", confirmedCount: 0 },
  { country: "Zambia", confirmedCount: 0 },
  { country: "Barbados", confirmedCount: 0 },
  { country: "Uganda", confirmedCount: 0 },
  { country: "El Salvador", confirmedCount: 0 },
  { country: "Togo", confirmedCount: 0 },
  { country: "Niger", confirmedCount: 0 },
  { country: "Ethiopia", confirmedCount: 0 },
  { country: "Mali", confirmedCount: 0 },
  { country: "Guinea", confirmedCount: 0 },
  { country: "Congo (Brazzaville)", confirmedCount: 0 },
  { country: "Tanzania", confirmedCount: 0 },
  { country: "Djibouti", confirmedCount: 0 },
  { country: "Maldives", confirmedCount: 0 },
  { country: "Gabon", confirmedCount: 0 },
  { country: "Eritrea", confirmedCount: 0 },
  { country: "Haiti", confirmedCount: 0 },
  { country: "Bahamas", confirmedCount: 0 },
  { country: "Burma", confirmedCount: 0 },
  { country: "Dominica", confirmedCount: 0 },
  { country: "Equatorial Guinea", confirmedCount: 0 },
  { country: "Mongolia", confirmedCount: 0 },
  { country: "Namibia", confirmedCount: 0 },
  { country: "Seychelles", confirmedCount: 0 },
  { country: "Syria", confirmedCount: 0 },
  { country: "Eswatini", confirmedCount: 0 },
  { country: "Grenada", confirmedCount: 0 },
  { country: "Laos", confirmedCount: 0 },
  { country: "Saint Lucia", confirmedCount: 0 },
  { country: "Guinea-Bissau", confirmedCount: 0 },
  { country: "Guyana", confirmedCount: 0 },
  { country: "Libya", confirmedCount: 0 },
  { country: "Mozambique", confirmedCount: 0 },
  { country: "Suriname", confirmedCount: 0 },
  { country: "Zimbabwe", confirmedCount: 0 },
  { country: "Angola", confirmedCount: 0 },
  { country: "Antigua and Barbuda", confirmedCount: 0 },
  { country: "Chad", confirmedCount: 0 },
  { country: "Saint Kitts and Nevis", confirmedCount: 0 },
  { country: "Sudan", confirmedCount: 0 },
  { country: "Benin", confirmedCount: 0 },
  { country: "Cabo Verde", confirmedCount: 0 },
  { country: "Holy See", confirmedCount: 0 },
  { country: "Mauritania", confirmedCount: 0 },
  { country: "Fiji", confirmedCount: 0 },
  { country: "Nepal", confirmedCount: 0 },
  { country: "Bhutan", confirmedCount: 0 },
  { country: "Gambia", confirmedCount: 0 },
  { country: "Nicaragua", confirmedCount: 0 },
  { country: "Belize", confirmedCount: 0 },
  { country: "Botswana", confirmedCount: 0 },
  { country: "Central African Republic", confirmedCount: 0 },
  { country: "Liberia", confirmedCount: 0 },
  { country: "Somalia", confirmedCount: 0 },
  { country: "MS Zaandam", confirmedCount: 0 },
  { country: "Papua New Guinea", confirmedCount: 0 },
  { country: "Saint Vincent and the Grenadines", confirmedCount: 0 },
  { country: "Timor-Leste", confirmedCount: 0 },
]
